const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { JSDOM, VirtualConsole } = require('jsdom');
const html = fs.readFileSync(path.join(__dirname, 'index.html'), 'utf8');
const app = fs.readFileSync(path.join(__dirname, 'app.js'), 'utf8');
const base = 'http://127.0.0.1:8765/roadmap/curriculum/gpu/course-site/index.html';
const pause = () => new Promise(resolve => setTimeout(resolve, 30));
const sessions = [];
function traverseHistory(env, direction) {
  return new Promise((resolve, reject) => {
    const onPop = () => { clearTimeout(timer); resolve(); };
    const timer = setTimeout(() => {
      env.w.removeEventListener('popstate',onPop);
      reject(new Error('Timed out waiting for history '+direction));
    },5000);
    env.w.addEventListener('popstate',onPop,{once:true});
    env.w.history[direction]();
  });
}
function boot(suffix) {
  const errors = [];
  const vc = new VirtualConsole();
  vc.on('jsdomError', error => errors.push(error));
  const dom = new JSDOM(html, {url: base + suffix, runScripts:'outside-only', virtualConsole:vc, pretendToBeVisual:true});
  sessions.push(dom);
  const w = dom.window;
  const headingCache = new WeakMap();
  w.__scrollTarget = '';
  w.scrollTo = () => { w.__scrollTarget = ''; };
  w.HTMLElement.prototype.scrollIntoView = function() { w.__scrollTarget = this.id; };
  w.HTMLElement.prototype.getBoundingClientRect = function() {
    const article = this.closest('.chapter');
    let heads = article ? headingCache.get(article) : [];
    if (article && (!heads || !heads[0]?.isConnected)) {
      heads = [...article.querySelectorAll('.markdown-body h2,.markdown-body h3')];
      headingCache.set(article, heads);
    }
    const target = heads.findIndex(h => h.id === w.__scrollTarget);
    const rank = heads.indexOf(this);
    return {top:(rank-Math.max(0,target))*200+90,bottom:0,left:0,right:0,width:800,height:30,x:0,y:0,toJSON(){}};
  };
  w.eval(app);
  return {w,d:w.document,errors};
}
function click(env, selector) {
  const element = env.d.querySelector(selector);
  assert(element, 'Missing clickable: ' + selector);
  element.click();
  return element;
}
function state(env, chapter, part) {
  const {d,w} = env;
  assert.equal(new URL(w.location.href).searchParams.get('chapter'), String(chapter));
  const shown = [...d.querySelectorAll('.chapter')].filter(a => !a.hidden);
  assert.equal(shown.length,1);
  assert.equal(shown[0].dataset.chapter,String(chapter));
  for(const panel of d.querySelectorAll('[data-sidebar-part]')) {
    assert.equal(panel.hidden, panel.dataset.sidebarPart !== part);
  }
  assert(d.querySelector('[data-sidebar-part="'+part+'"]'), 'Missing active side panel');
  assert(d.querySelector('[data-part-link="'+part+'"]').classList.contains('active'));
  assert(d.querySelector('details[data-nav-chapter="'+chapter+'"]').open, 'Current chapter must open on navigation');
}
(async () => {
  const e=boot('?chapter=2');
  state(e,2,'gpu');
  click(e,'[data-part-link="operators"]');
  state(e,7,'operators');
  click(e,'[data-sidebar-part="operators"] [data-chapter-link="7"]');
  state(e,7,'operators');
  // Keep the original chapter-8 fold/anchor coverage intact.
  click(e,'[data-sidebar-part="operators"] [data-chapter-link="8"]');
  state(e,8,'operators');
  const sub8=click(e,'details[data-nav-chapter="8"] a[href*="#"]');
  assert.equal(e.w.location.hash,sub8.hash);
  assert.equal(e.w.__scrollTarget,sub8.hash.slice(1));
  const details8=e.d.querySelector('details[data-nav-chapter="8"]');
  const before8=e.w.location.href;
  click(e,'details[data-nav-chapter="8"] summary');
  await pause();
  assert.equal(details8.open,false,'Summary must fold');
  assert.equal(e.w.location.href,before8,'Folding must not navigate');
  e.w.dispatchEvent(new e.w.Event('scroll'));
  await pause();
  assert.equal(details8.open,false,'Scrolling must not reopen a manually folded chapter');
  click(e,'details[data-nav-chapter="8"] summary');
  await pause();
  assert(details8.open);
  // Chapter 9 gets its own anchor and previous/next route coverage.
  click(e,'[data-sidebar-part="operators"] [data-chapter-link="9"]');
  state(e,9,'operators');
  const sub9=click(e,'details[data-nav-chapter="9"] a[href*="#"]');
  assert.equal(e.w.location.hash,sub9.hash);
  assert.equal(e.w.__scrollTarget,sub9.hash.slice(1));
  click(e,'#chapter-9 .chapter-switch a[data-chapter-link="8"]');
  state(e,8,'operators');
  click(e,'#chapter-8 .chapter-switch a[data-chapter-link="9"]');
  state(e,9,'operators');
  click(e,'#chapter-9 .chapter-switch a[data-chapter-link="10"]');
  state(e,10,'operators');
  const sub10=click(e,'details[data-nav-chapter="10"] a[href*="#"]');
  assert.equal(e.w.location.hash,sub10.hash);
  assert.equal(e.w.__scrollTarget,sub10.hash.slice(1));
  const details10=e.d.querySelector('details[data-nav-chapter="10"]');
  const before10=e.w.location.href;
  click(e,'details[data-nav-chapter="10"] summary');
  await pause();
  assert.equal(details10.open,false);
  assert.equal(e.w.location.href,before10);
  click(e,'details[data-nav-chapter="10"] summary');
  await pause();
  assert(details10.open);
  click(e,'#chapter-10 .chapter-switch a[data-chapter-link="11"]');
  state(e,11,'operators');
  const sub11=click(e,'details[data-nav-chapter="11"] a[href*="#"]');
  assert.equal(e.w.location.hash,sub11.hash);
  assert.equal(e.w.__scrollTarget,sub11.hash.slice(1));
  const details11=e.d.querySelector('details[data-nav-chapter="11"]');
  const before11=e.w.location.href;
  click(e,'details[data-nav-chapter="11"] summary');
  await pause();
  assert.equal(details11.open,false);
  assert.equal(e.w.location.href,before11);
  click(e,'details[data-nav-chapter="11"] summary');
  await pause();
  assert(details11.open);
  click(e,'#chapter-11 .chapter-switch a[data-chapter-link="12"]');
  state(e,12,'operators');
  const sub12=click(e,'details[data-nav-chapter="12"] a[href*="#"]');
  assert.equal(e.w.location.hash,sub12.hash);
  const before12=e.w.location.href;
  click(e,'details[data-nav-chapter="12"] summary');
  await pause();
  assert.equal(e.d.querySelector('details[data-nav-chapter="12"]').open,false);
  assert.equal(e.w.location.href,before12);
  click(e,'details[data-nav-chapter="12"] summary');
  await pause();
  click(e,'#chapter-12 .chapter-switch a[data-chapter-link="11"]');
  state(e,11,'operators');
  click(e,'#chapter-11 .chapter-switch a[data-chapter-link="10"]');
  state(e,10,'operators');
  click(e,'#chapter-10 .chapter-switch a[data-chapter-link="9"]');
  state(e,9,'operators');
  click(e,'[data-sidebar-part="operators"] [data-chapter-link="7"]');
  state(e,7,'operators');
  click(e,'[data-part-link="gpu"]');
  state(e,2,'gpu');
  click(e,'[data-part-link="operators"]');
  state(e,7,'operators');
  await traverseHistory(e,'back'); state(e,2,'gpu');
  await traverseHistory(e,'forward'); state(e,7,'operators');
  click(e,'[data-part-link="gpu"]');
  const search=e.d.querySelector('#search');
  const sidebar=e.d.querySelector('.sidebar');
  const chapterNav=e.d.querySelector('#chapter-nav');
  const searchResults=e.d.querySelector('#search-results');
  assert.equal(search.parentElement.nextElementSibling,searchResults,'Results must immediately follow the search field');
  search.value='Runtime API：同步行为';search.dispatchEvent(new e.w.Event('input',{bubbles:true}));
  assert.equal(chapterNav.hidden,true,'A non-empty query must hide the chapter directory');
  assert.equal(searchResults.hidden,false);
  assert(searchResults.querySelectorAll('.search-result').length>0,'Markdown link labels should be searchable');
  assert([...searchResults.querySelectorAll('.search-result small')].some(snippet=>snippet.textContent.includes('Runtime API：同步行为')),'Snippet should retain the Markdown link label');
  assert([...searchResults.querySelectorAll('.search-result small')].every(snippet=>!snippet.textContent.includes('api-sync-behavior.html')),'Search snippets must omit the Markdown link target');
  sidebar.scrollTop=240;
  search.value='no-course-result-should-match-7fd31';search.dispatchEvent(new e.w.Event('input',{bubbles:true}));
  assert.equal(sidebar.scrollTop,0,'Searching must return the sidebar to its top');
  assert.equal(chapterNav.hidden,true,'No-result queries still replace the directory');
  assert.equal(searchResults.hidden,false);
  assert.match(searchResults.textContent,/没有匹配内容/);
  search.value='';search.dispatchEvent(new e.w.Event('input',{bubbles:true}));
  assert.equal(searchResults.hidden,true,'Clearing the query must hide results');
  assert.equal(chapterNav.hidden,false,'Clearing the query must restore the directory');
  search.value='float4';search.dispatchEvent(new e.w.Event('input',{bubbles:true}));
  const modifiedResult=e.d.querySelector('#search-results a[href*="chapter=7"]');
  assert(modifiedResult);
  const beforeModifiedClick=e.w.location.href;
  modifiedResult.addEventListener('click',event=>event.preventDefault(),{once:true});
  modifiedResult.dispatchEvent(new e.w.MouseEvent('click',{bubbles:true,cancelable:true,ctrlKey:true}));
  assert.equal(e.w.location.href,beforeModifiedClick,'Ctrl-click must keep its native new-tab behavior');
  assert.equal(search.value,'float4','Modified clicks must not clear the active search');
  assert.equal(chapterNav.hidden,true);
  search.value='float4';search.dispatchEvent(new e.w.Event('input',{bubbles:true}));
  click(e,'#search-results a[href*="chapter=7"]');
  state(e,7,'operators');
  assert.equal(search.value,'','Selecting a search result must clear the query');
  assert.equal(searchResults.hidden,true);
  assert.equal(chapterNav.hidden,false,'Selecting a search result must restore the directory');
  search.value='GEMM';search.dispatchEvent(new e.w.Event('input',{bubbles:true}));
  e.w.courseNavigation.navigate('?chapter=8');
  state(e,8,'operators');
  assert.equal(search.value,'','Normal navigation must clear an active search');
  assert.equal(searchResults.hidden,true);
  assert.equal(chapterNav.hidden,false,'Normal navigation must restore the directory');
  search.value='GEMM';search.dispatchEvent(new e.w.Event('input',{bubbles:true}));
  click(e,'#search-results a[href*="chapter=9"]');
  state(e,9,'operators');
  search.value='SwiGLU';search.dispatchEvent(new e.w.Event('input',{bubbles:true}));
  click(e,'#search-results a[href*="chapter=10"]');
  state(e,10,'operators');
  search.value='Prefill Attention';search.dispatchEvent(new e.w.Event('input',{bubbles:true}));
  click(e,'#search-results a[href*="chapter=11"]');
  state(e,11,'operators');
  const deep=e.d.querySelector('details[data-nav-chapter="9"] a[href*="#"]');
  search.value='PagedAttention';search.dispatchEvent(new e.w.Event('input',{bubbles:true}));
  click(e,'#search-results a[href*="chapter=12"]');
  state(e,12,'operators');
  const targetHash=deep.hash;
  click(e,'#chapter-10 .chapter-switch a[data-chapter-link="9"]');
  state(e,9,'operators');
  click(e,'#chapter-9 .chapter-switch a[data-chapter-link="8"]');
  state(e,8,'operators');
  click(e,'#chapter-8 .chapter-switch a[data-chapter-link="7"]');
  state(e,7,'operators');
  click(e,'#chapter-7 .chapter-switch a[data-chapter-link="5"]');
  state(e,5,'gpu');
  click(e,'[data-part-link="gpu"]');
  click(e,'[data-sidebar-part="gpu"] summary a[data-chapter-link="5"]');
  state(e,5,'gpu');
  click(e,'#chapter-5 .chapter-switch a[data-chapter-link="7"]');
  state(e,7,'operators');
  const reloaded=boot('?chapter=9'+targetHash);
  state(reloaded,9,'operators');
  assert.equal(reloaded.w.__scrollTarget,targetHash.slice(1),'Direct fragment must scroll');
  const reloaded10=boot('?chapter=10'+sub10.hash);
  state(reloaded10,10,'operators');
  assert.equal(reloaded10.w.__scrollTarget,sub10.hash.slice(1));
  const reloaded11=boot('?chapter=11'+sub11.hash);
  state(reloaded11,11,'operators');
  assert.equal(reloaded11.w.__scrollTarget,sub11.hash.slice(1));
  const reloaded12=boot('?chapter=12'+sub12.hash);
  state(reloaded12,12,'operators');
  assert.equal(reloaded12.w.__scrollTarget,sub12.hash.slice(1));
  const remaining=boot('?chapter=12');
  for (const next of [13,14,15]) {
    click(remaining,'#chapter-'+(next-1)+' .chapter-switch a[data-chapter-link="'+next+'"]');
    state(remaining,next,'operators');
    const link=click(remaining,'details[data-nav-chapter="'+next+'"] a[href*="#"]');
    assert.equal(remaining.w.location.hash,link.hash);
    click(remaining,'details[data-nav-chapter="'+next+'"] summary');await pause();
    assert.equal(remaining.d.querySelector('details[data-nav-chapter="'+next+'"]').open,false);
    click(remaining,'details[data-nav-chapter="'+next+'"] summary');await pause();
  }
  click(remaining,'#chapter-15 .chapter-switch a[data-chapter-link="14"]');
  state(remaining,14,'operators');
  const searchRemaining=remaining.d.querySelector('#search');
  searchRemaining.value='量化算子';searchRemaining.dispatchEvent(new remaining.w.Event('input',{bubbles:true}));
  click(remaining,'#search-results a[href*="chapter=13"]');state(remaining,13,'operators');
  assert.equal(remaining.errors.length,0);
  const applications=boot('?chapter=15');
  click(applications,'#chapter-15 .chapter-switch a[data-chapter-link="16"]');
  state(applications,16,'systems');
  click(applications,'[data-part-link="operators"]');state(applications,15,'operators');
  click(applications,'[data-part-link="systems"]');state(applications,16,'systems');
  for(const id of [17,18,19]) {
    click(applications,'#chapter-'+(id-1)+' .chapter-switch a[data-chapter-link="'+id+'"]');
    state(applications,id,'systems');
  }
  const sub19=click(applications,'details[data-nav-chapter="19"] a[href*="#"]');
  click(applications,'details[data-nav-chapter="19"] summary');await pause();
  assert.equal(applications.d.querySelector('details[data-nav-chapter="19"]').open,false);
  click(applications,'details[data-nav-chapter="19"] summary');await pause();
  const applicationSearch=applications.d.querySelector('#search');
  applicationSearch.value='prefix_identity';
  applicationSearch.dispatchEvent(new applications.w.Event('input',{bubbles:true}));
  click(applications,'#search-results a[href*="chapter=18"]');state(applications,18,'systems');
  await traverseHistory(applications,'back');state(applications,19,'systems');
  assert(!applications.d.querySelector('#chapter-19 .chapter-switch a[data-chapter-link="1"]'));
  const direct19=boot('?chapter=19'+sub19.hash);state(direct19,19,'systems');
  assert.equal(direct19.w.__scrollTarget,sub19.hash.slice(1));
  assert.equal(applications.errors.length,0);assert.equal(direct19.errors.length,0);
  const legacyOverview=boot('?chapter=6#chapter-6-section-0');
  state(legacyOverview,7,'operators');
  assert.equal(legacyOverview.w.location.hash,'');
  assert(!legacyOverview.d.querySelector('#chapter-6'));
  assert.equal(legacyOverview.errors.length,0);
  const invalid=boot('?chapter=999');
  state(invalid,1,'gpu');
  for(const env of [e,reloaded,reloaded10,reloaded11,reloaded12,invalid]) assert.equal(env.errors.length,0,env.errors.map(x=>x.message).join('\n'));
  console.log('PASS: top/side coordination; partition memory; subsection routes; folding; scroll; back/forward; search; chapter 12->13->14->15 and return; direct fragments; invalid route.');
  console.log('DOM simulation only: layout and scroll positions are modeled, not a visual browser test.');
})().catch(error=>{console.error(error);process.exitCode=1;}).finally(()=>sessions.forEach(dom=>dom.window.close()));
